version: '2'
services:
  redis-master:
    image: redis:5.0.4
    container_name: redis-master
    volumes:
      - "./data/redis:/data"
    ports:
      - 6380:6380
    command: redis-server --appendonly yes --port 6380 --slave-announce-ip 192.168.20.143
  redis-slave-1:
    image: redis:5.0.4
    container_name: redis-slave-1
    ports:
      - 6381:6381
    command: redis-server --port 6381 --slaveof 192.168.20.143 6380 --slave-announce-ip 192.168.20.143
  redis-slave-2:
    image: redis:5.0.4
    container_name: redis-slave-2
    ports:
      - 6382:6382
    command: redis-server --port 6382 --slaveof 192.168.20.143 6380 --slave-announce-ip 192.168.20.143
  redis-sentinel-1:
    image: redis:5.0.4
    container_name: redis-sentinel-1
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
      - 26380:26380
    volumes:
      - ./sentinel-1.conf:/usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
  redis-sentinel-2:
    image: redis:5.0.4
    container_name: redis-sentinel-2
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
      - 26381:26381
    volumes:
      - ./sentinel-2.conf:/usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
  redis-sentinel-3:
    image: redis:5.0.4
    container_name: redis-sentinel-3
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    ports:
      - 26382:26382
    volumes:
      - ./sentinel-3.conf:/usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master